# **Comprehensive Tutorial on NumPy for Python**

NumPy (Numerical Python) is a powerful library for numerical computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on them. NumPy is the foundation for many other libraries like Pandas, Matplotlib, and Scikit-learn, making it an essential tool for data science, AI, and scientific computing.


Features of NumPy

1. Efficient storage and manipulation of multi-dimensional arrays.


2. Support for mathematical and statistical operations.


3. Broadcasting for performing operations on arrays of different shapes.


4. Integration with other libraries and frameworks.


5. Vast support for linear algebra and random number generation

NumPy Tutorial Outline

This tutorial will cover the following sections:

1. Introduction to NumPy


2. Creating Arrays


3. Array Attributes


4. Indexing and Slicing


5. Array Operations


6. Broadcasting


7. Mathematical Functions


8. Statistical Functions


9. Linear Algebra


10. Random Numbers


11. Performance Comparison: NumPy vs Python Lists

# **Step-by-Step Tutorial**

# **1. Installing and Importing NumPy**

In [1]:
# Install NumPy if not already installed
!pip install numpy

# Importing the NumPy library
import numpy as np

# **2. Creating Arrays**

NumPy arrays are the core of the library and come in two main types: 1D arrays (vectors) and 2D arrays (matrices).

In [3]:
#Creating a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)

# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)

# Creating arrays using functions
zeros = np.zeros((3, 3))  # 3x3 matrix of zeros
ones = np.ones((2, 4))  # 2x4 matrix of ones
range_array = np.arange(0, 10, 2)  # Values from 0 to 10 with step 2
linspace = np.linspace(0, 1, 5)  # 5 equally spaced values between 0 and 1

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Range Array:", range_array)
print("Linspace:", linspace)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Range Array: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]


# **3. Array Attributes**

Understand the properties of an array:

In [4]:
# Array attributes
print("Shape:", array_2d.shape)  # Dimensions of the array
print("Number of dimensions:", array_2d.ndim)
print("Size (total elements):", array_2d.size)
print("Data type:", array_2d.dtype)


Shape: (2, 3)
Number of dimensions: 2
Size (total elements): 6
Data type: int64


# **4. Indexing and Slicing**

Access elements or subsets of an array.

In [5]:
# Indexing
element = array_2d[1, 2]  # Element in 2nd row, 3rd column
print("Element:", element)

# Slicing
slice_1d = array_1d[1:4]  # From index 1 to 3
slice_2d = array_2d[:, 1]  # All rows, 2nd column

print("Slice 1D:", slice_1d)
print("Slice 2D:\n", slice_2d)

Element: 6
Slice 1D: [2 3 4]
Slice 2D:
 [2 5]


# **5. Array Operations**

Perform element-wise operations:

In [6]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Element-wise addition, subtraction, multiplication, division
print("Addition:", array1 + array2)
print("Subtraction:", array1 - array2)
print("Multiplication:", array1 * array2)
print("Division:", array1 / array2)

# Scalar operations
print("Array * 2:", array1 * 2)


Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Array * 2: [2 4 6]


# **6. Broadcasting**

Handle arrays of different shapes:

In [7]:
# Broadcasting example
array3 = np.array([[1], [2], [3]])  # Shape (3, 1)
array4 = np.array([10, 20, 30])  # Shape (1, 3)

result = array3 + array4  # Broadcasting
print("Broadcasting Result:\n", result)


Broadcasting Result:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


# **7. Mathematical Functions**

In [8]:
array = np.array([1, 2, 3, 4, 5])

# Basic math
print("Square Root:", np.sqrt(array))
print("Exponential:", np.exp(array))
print("Logarithm:", np.log(array))
print("Sum:", np.sum(array))
print("Mean:", np.mean(array))
print("Standard Deviation:", np.std(array))


Square Root: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Logarithm: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Sum: 15
Mean: 3.0
Standard Deviation: 1.4142135623730951


# **8. Statistical Functions**

In [9]:
array = np.array([[1, 2, 3], [4, 5, 6]])

# Aggregation
print("Maximum:", np.max(array))
print("Minimum:", np.min(array))
print("Row-wise Sum:", np.sum(array, axis=1))
print("Column-wise Mean:", np.mean(array, axis=0))


Maximum: 6
Minimum: 1
Row-wise Sum: [ 6 15]
Column-wise Mean: [2.5 3.5 4.5]


# **9. Linear Algebra**

NumPy provides efficient methods for linear algebra operations.

In [10]:
matrix = np.array([[1, 2], [3, 4]])
vector = np.array([5, 6])

# Matrix multiplication
result = np.dot(matrix, vector)
print("Matrix-Vector Multiplication:\n", result)

# Determinant
print("Determinant:", np.linalg.det(matrix))

# Inverse
inverse = np.linalg.inv(matrix)
print("Inverse Matrix:\n", inverse)


Matrix-Vector Multiplication:
 [17 39]
Determinant: -2.0000000000000004
Inverse Matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


# **10. Random Numbers**

Generate random data for testing or simulations.

In [11]:
# Random array
random_array = np.random.rand(3, 3)  # 3x3 matrix with values in [0, 1]
random_int = np.random.randint(1, 10, (2, 2))  # Random integers

print("Random Array:\n", random_array)
print("Random Integers:\n", random_int)


Random Array:
 [[0.97164321 0.53803633 0.97018685]
 [0.68575227 0.76315007 0.25303456]
 [0.87587652 0.84045412 0.86504619]]
Random Integers:
 [[5 8]
 [9 3]]


# **11. Performance Comparison: NumPy vs Python Lists**

In [12]:
import time

# Using Python lists
python_list = list(range(1000000))
start_time = time.time()
python_sum = sum(python_list)
end_time = time.time()
print("Python List Sum:", python_sum, "Time:", end_time - start_time)

# Using NumPy arrays
numpy_array = np.arange(1000000)
start_time = time.time()
numpy_sum = np.sum(numpy_array)
end_time = time.time()
print("NumPy Array Sum:", numpy_sum, "Time:", end_time - start_time)


Python List Sum: 499999500000 Time: 0.013781070709228516
NumPy Array Sum: 499999500000 Time: 0.0009264945983886719


# **Conclusion**

NumPy is a powerful tool for scientific computing, offering efficient operations for arrays and matrices, a wide range of mathematical functions, and seamless integration with other libraries. By mastering NumPy, you gain a foundation for data science, AI, and computational tasks.
